title: "AIC Scientific Magazine"
email: editor@aic-magazine.org
description: "الموقع الرسمي لمجلة AIC العلمية"
baseurl: "/aic-magazine"
url: "https://chiefeditor2025.github.io"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
